# Forex Trading AI Platform Configuration

platform:
  name: Forex Trading AI Platform
  version: 0.1.0
  cycle_interval: 60  # seconds
  log_level: INFO

market_data:
  api_provider: example_provider
  api_key: your_api_key_here
  symbols:
    - EUR/USD
    - GBP/USD
    - USD/JPY
    - AUD/USD
  timeframes:
    - 1m
    - 5m
    - 15m
    - 1h
    - 4h
    - 1d
  data_dir: ../data/market_data

technical_analysis:
  indicators:
    moving_averages:
      - SMA
      - EMA
      - WMA
    oscillators:
      - RSI
      - MACD
      - Stochastic
    volatility:
      - Bollinger Bands
      - ATR
    trend:
      - ADX
      - Ichimoku
  lookback_periods:
    short_term: 14
    medium_term: 50
    long_term: 200
  # Trading strategies configuration with optimized parameters
  strategies:
    active_strategies:
      - rsi_reversal         # Prioritize the most profitable strategy
      - bollinger_bands
      - macd
      - moving_average_crossover
    # Strategy-specific risk parameters
    risk_per_strategy:
      rsi_reversal: 0.025    # 2.5% risk for best performer
      bollinger_bands: 0.015 # 1.5% risk
      macd: 0.01             # 1% risk (reduced)
      moving_average_crossover: 0.0075 # 0.75% risk until proven
    # Enhanced RSI Reversal Strategy - performed best in testing
    rsi_reversal:
      rsi_period: 14
      oversold: 25           # Tightened from 30 for stronger signals
      overbought: 75         # Tightened from 70 for stronger signals
      confirmation_ma_period: 20 # New: MA confirmation
      timeframes: ["1h", "4h"]
      symbols: ["EUR/USD", "GBP/USD", "USD/JPY"]
    # Enhanced Bollinger Bands Strategy
    bollinger_bands:
      period: 20
      std_dev: 2.5           # Widened from 2.0 to reduce false signals
      rsi_filter_period: 14  # New: RSI filter
      rsi_lower_threshold: 40 # New: Only buy when RSI < 40
      rsi_upper_threshold: 60 # New: Only sell when RSI > 60
      timeframes: ["1h", "4h"]
      symbols: ["EUR/USD", "USD/JPY"]
    # Enhanced MACD Strategy
    macd:
      fast_period: 12
      slow_period: 26
      signal_period: 9
      histogram_threshold: 0.0005 # New: Minimum histogram value
      trend_ma_period: 50         # New: Trend filter
      timeframes: ["1h", "4h", "1d"]
      symbols: ["EUR/USD", "GBP/USD", "AUD/USD"]
    # Enhanced Moving Average Crossover
    moving_average_crossover:
      fast_period: 5          # Changed from 10 for more sensitivity
      slow_period: 20         # Changed from 50 for more sensitivity
      volume_threshold: 1.5   # New: Only trade when volume > 1.5x average
      volume_period: 20       # New: Period for volume average
      timeframes: ["1h", "4h"]
      symbols: ["EUR/USD", "GBP/USD"]
    # Common risk management parameters
    risk_management:
      max_positions: 3         # Maximum concurrent positions
      reward_risk_ratio: 2     # Target 2:1 reward-to-risk
      trailing_stop_atr: 2.5   # Trailing stop at 2.5 ATR
      atr_period: 14           # Period for ATR calculation
      max_trade_duration: 48   # Close trades after 48 hours
      correlation_threshold: 0.7 # Avoid highly correlated trades

fundamentals:
  data_sources:
    - economic_calendar
    - central_bank_announcements
    - economic_indicators
  api_keys:
    news_api: your_news_api_key_here
    economic_data: your_economic_data_api_key_here

sentiment:
  data_sources:
    - twitter
    - news
    - reddit
  api_keys:
    twitter: your_twitter_api_key_here
    news: your_news_api_key_here
  models:
    nlp_model: distilbert-base-uncased
    sentiment_threshold: 0.5

risk_management:
  max_risk_per_trade: 0.02  # 2% of account
  max_open_positions: 5
  max_risk_per_currency: 0.05  # 5% of account
  max_daily_drawdown: 0.05  # 5% of account
  stop_loss_atr_multiplier: 2.0

portfolio_management:
  account_size: 10000
  leverage: 30
  position_sizing_method: risk_based  # Alternatives: fixed_lot, percent_based
  broker:
    name: example_broker
    api_key: your_broker_api_key_here
    api_secret: your_broker_api_secret_here 